# Debug Settings
DEBUG_MODE = False
DEBUG_SPEED_MULTIPLIER = 100

# Base Timer Settings
DEFAULT_START_TIME = 300
DEFAULT_TICK_DELAY_MS = 1000

# UI Styles
BG_COLOR = "#2e2e2e"
TEXT_COLOR = "#ffffff"
DONE_COLOR = "#ff5555"

# Event Odds
CHANCE_INCREASING = 33
CHANCE_NEUTRAL = 34
CHANCE_DECREASING = 33